<template>
  <router-view></router-view>
</template>

<script setup lang="ts">
import useTheme from '@/hooks/useTheme'
import {} from 'vue'
import apis from './api/apis'
import { userStore } from './stores/user'
useTheme()

// Mock user data for when API is unavailable
const mockUserInfo = {
  status_code: 0,
  status_msg: 'success',
  user: {
    uid: 'mock_uid',
    short_id: 'mock_short_id',
    nickname: '抖音用户',
    gender: 0,
    signature: '记录美好生活',
    avatar_168x168: { uri: '', url_list: [], width: 168, height: 168 },
    avatar_300x300: { uri: '', url_list: [], width: 300, height: 300 },
    avatar_larger: { uri: '', url_list: [], width: 400, height: 400 },
    avatar_medium: { uri: '', url_list: [], width: 200, height: 200 },
    avatar_thumb: { uri: '', url_list: [], width: 100, height: 100 },
    aweme_count: 0,
    aweme_count_correction_threshold: '',
    birthday: '',
    birthday_hide_level: 0,
    can_set_item_cover: false,
    can_show_group_card: 0,
    city: '',
    district: '',
    school_name: '',
    close_friend_type: 0,
    country: '',
    ip_location: '',
    is_verified: false,
    follow_status: 0,
    following_count: 0,
    follower_count: 0,
    mplatform_followers_count: 0,
    favoriting_count: 0,
    total_favorited: 0,
    is_block: false,
    hide_search: false,
    constellation: 0,
    disable_image_comment_saved: 0,
    hide_location: false,
    weibo_verify: '',
    custom_verify: '',
    unique_id: '',
    verification_permission_ids: null,
    special_lock: 0,
    need_recommend: 0,
    is_binded_weibo: false,
    weibo_name: '',
    weibo_schema: '',
    weibo_url: '',
    story_open: false,
    story_count: 0,
    has_facebook_token: false,
    fb_expire_time: 0,
    has_twitter_token: false,
    tw_expire_time: 0,
    has_youtube_token: false,
    youtube_expire_time: 0,
    room_id: 0,
    live_verify: 0,
    authority_status: 0,
    verify_info: '',
    shield_follow_notice: 0,
    shield_digg_notice: 0,
    shield_comment_notice: 0,
    profile_mob_params: null,
    show_favorite_list: true,
    show_subscription: false,
    avatar_schema_list: null,
    awemehts_greet_info: '',
    with_commerce_entry: false,
    verification_type: 0,
    enterprise_verify_reason: '',
    is_ad_fake: false,
    live_high_value: 0,
    region: '',
    account_region: '',
    sync_to_toutiao: 0,
    commerce_user_level: 0,
    live_agreement: 0,
    platform_sync_info: null,
    with_shop_entry: false,
    is_discipline_member: false,
    secret: 0,
    has_orders: false,
    prevent_download: false,
    show_image_bubble: false,
    geofencing: [],
    unique_id_modify_time: 0,
    video_icon: { uri: '', url_list: [], width: 0, height: 0 },
    ins_id: '',
    google_account: '',
    youtube_channel_id: '',
    youtube_channel_title: '',
    apple_account: 0,
    with_dou_entry: false,
    with_fusion_shop_entry: false,
    is_phone_binded: false,
    accept_private_policy: false,
    twitter_id: '',
    twitter_name: '',
    user_canceled: false,
    has_email: false,
    is_gov_media_vip: false,
    live_agreement_time: 0,
    status: 0,
    avatar_uri: '',
    follower_status: 0,
    neiguang_shield: 0,
    comment_setting: 0,
    duet_setting: 0,
    reflow_page_gid: 0,
    reflow_page_uid: 0,
    user_rate: 0,
    download_setting: 0,
    download_prompt_ts: 0,
    react_setting: 0,
    live_commerce: false,
    cover_url: [],
    show_gender_strategy: 0,
    language: '',
    has_insights: false,
    item_list: null,
    user_mode: 0,
    user_period: 0,
    has_unread_story: false,
    new_story_cover: null,
    is_star: false,
    cv_level: '',
    type_label: null,
    ad_cover_url: '',
    comment_filter_status: 0,
    relative_users: null,
    cha_list: null,
    sec_uid: 'mock_sec_uid',
    urge_detail: undefined,
    need_points: null,
    homepage_bottom_toast: null,
    aweme_hotsoon_auth: 0,
    aweme_hotsoon_auth_relation: 0,
    can_set_geofencing: null,
    room_id_str: '',
    white_cover_url: undefined,
    user_tags: null,
    stitch_setting: 0,
    is_mix_user: false,
    enable_nearby_visible: false,
    ban_user_functions: [],
    aweme_control: { can_forward: true, can_share: true, can_comment: true, can_show_comment: true },
    user_not_show: 0,
    ky_only_predict: 0,
    user_not_see: 0,
    card_entries: null,
    signature_display_lines: 2,
    display_info: null,
    follower_request_status: 0,
    live_status: 0,
    new_friend_type: 0,
    is_not_show: false,
    card_entries_not_display: null,
    card_sort_priority: null,
    show_nearby_active: false,
    interest_tags: null,
    school_category: 0,
    search_impr: { entity_id: '' },
    link_item_list: null,
    user_permissions: null,
    offline_info_list: null,
    is_cf: 0,
    is_blocking_v2: false,
    is_blocked_v2: false,
    general_permission: undefined,
    signature_extra: null,
    max_follower_count: 0,
    personal_tag_list: null,
    cf_list: null,
    im_role_ids: null,
    not_seen_item_id_list: null,
    familiar_visitor_user: null,
    contacts_status: 0,
    risk_notice_text: '',
    follower_list_secondary_information_struct: null,
    endorsement_info_list: null,
    text_extra: null,
    contrail_list: null,
    data_label_list: null,
    not_seen_item_id_list_v2: null,
    is_ban: false,
    special_people_labels: null,
    special_follow_status: 0
  },
  user_collect_count: {
    collect_count_list: []
  }
}

const user = userStore()
const get_user_info = async () => {
  try {
    const user_info = await apis.getUserInfo()
    if (user_info.status_code === 0) {
      user.userInfo = user_info
      user.isLogin = true
    } else {
      user.isLogin = false
    }
  } catch {
    user.userInfo = mockUserInfo as any
    user.isLogin = false
  }
}
onMounted(() => {
  get_user_info()
})
</script>
<style lang="scss" scoped></style>
